name: Publish to CPAN

on:
  release:
    types: [created]

jobs:
  publish-ui:
    name: Publish to CPAN
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v2
      - name: update-version
        run: |
          sed -i "s/^\\\$VERSION = '.*';/\\\$VERSION = '${GITHUB_REF_NAME}';/" lib/Test/MockModule.pm
      - uses: cucumber/action-publish-cpan@v1.0.0
        with:
          cpan-user: ${{ secrets.CPAN_USER }}
          cpan-password: ${{ secrets.CPAN_PASSWORD }}
          working-directory: "."
